### ISSUE TITLE
Convert VBA code to  vbs code or js code?

### ISSUE THREAD

**Issue by echotxl** [christophetd/spoofing-office-macro#6]
hi bro ,I really appreciate your writing this code。
but,Can you convert VBA code to  vbs code or js code ?  Vbs code or js codes is very userful 
I will be very grateful if you can

**Comment by christophetd** [comment]
Hello,

Glad you find the project useful. Yes, in theory almost anything written in VBA can be ported to VBS. I'm not sure about JS.

I do not currently plan to write a VBS or JS version of this code, but contributions are welcome.
